# Training configuration
mlflow_experiment_location: "/Shared/ml_production_experiment"
mlflow_model_registry_name: "ml_production_experiment"
feature_table_name: "default.passenger_featurs_combined"
validation_statistic_to_compare: "f1_testing"

# Scoring configuration
predictions_table: "default.passenger_predictions"



