# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# Useful tutorial: https://circleci.com/blog/publishing-a-python-package/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-tROAS-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=CjwKCAiAxvGfBhB-EiwAMPakqkhwFb8DT7tzxP7YFY-kdVR5nWMX4i9BGPr0DUXoWhpWys8SEmzLixoCs6wQAvD_BwE
# DATABRICKS_HOST and DATABRICKS_TOKEN

version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  integration_test:
    docker:
      - image: cimg/python:3.10.2
    environment: 
      DATABRICKS_HOST: $DATABRICKS_HOST_STAGING
      DATABRICKS_TOKEN: $DATABRICKS_TOKEN_STAGING
      TEST_VAR: test_var

    steps:
      - checkout
      - run:
          name: Environment variable configuration
          command: |
                  echo "export CURRENT_BRANCH=$CURRENT_BRANCH" >> "$BASH_ENV"
      - run:
          name: Print environment variables
          command: | 
                  echo $DATABRICKS_HOST
                  echo $DATABRICKS_TOKEN
                  echo $CURRENT_BRANCH
                  echo $TEST_VAR
      #- run:
      #    name: Install dependencies
      #    command: pip install -r requirements.txt
      #- run:
      #    name: Run integration test
      #    command: | 
      #            dbx deploy ml-prod-deployment-train-model --assets-only --no-package
      #            dbx launch ml-prod_deployment-train-model --from-assets --trace


workflows:
  main:
    jobs:
      - integration_test