# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# Useful tutorial: https://circleci.com/blog/publishing-a-python-package/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-tROAS-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=CjwKCAiAxvGfBhB-EiwAMPakqkhwFb8DT7tzxP7YFY-kdVR5nWMX4i9BGPr0DUXoWhpWys8SEmzLixoCs6wQAvD_BwE
# DATABRICKS_HOST and DATABRICKS_TOKEN

version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  integration_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name:  Configure Databricks environment variables
          command: | 
                  export DATABRICKS_HOST=$DATABRICKS_HOST_STAGING
                  export DATABRICKS_TOKEN=$DATABRICKS_TOKEN_STAGING
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run integration test
          command: | 
                  dbx deploy ml-prod-deployment-train-model --assets-only --no-package
                  dbx launch ml-prod_deployment-train-model --from-assets --trace


workflows:
  main:
    jobs:
      - integration_test



env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

