# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "11.3.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 0
      node_type_id: "i3.xlarge"
      spark_conf:
        spark.master: "local[*, 4]"
        spark.databricks.cluster.profile: "singleNode"
      custom_tags:
        ResourceClass: "SingleNode"


environments:
  default:
    workflows:
      #######################################################################################
      #   Populate Feature Table                                                            #
      #######################################################################################
      - name: "ml-prod-deployment-create-features"
        git_source:
          git_url: https://github.com/marshackVB/ml_prod_deployment.git
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "create-features"
            <<: *basic-static-cluster
            notebook_task:
              notebook_path: "ml_prod_deployment/data_generation/create_features"
            deployment_config:
              no_package: true
      #######################################################################################
      #   Train model                                                                       #
      #######################################################################################
      - name: "ml-prod-deployment-train-model"
        git_source:
          git_url: https://github.com/marshackVB/ml_prod_deployment.git
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "train-model"
            <<: *basic-static-cluster
            notebook_task:
              notebook_path: "ml_prod_deployment/trainer"
              base_parameters: {"compare_model_registry_versions" : "True"}
            deployment_config:
              no_package: true
      #######################################################################################
      #   Score records - one time run                                                      #
      #   Load the production model and score records from the training dataset as          #
      #   a one-off job. This job is designed to test the inference process                 #
      #######################################################################################
      - name: "ml-prod-deployment-score-records-one-time"
        git_source:
          git_url: https://github.com/marshackVB/ml_prod_deployment.git
          git_provider: "github"
          git_branch: "master"
        tasks:
          - task_key: "train-model"
            <<: *basic-static-cluster
            notebook_task:
              notebook_path: "ml_prod_deployment/inference"
              base_parameters: {"run_as_integration_test" : "True"}
            deployment_config:
              no_package: true
      #######################################################################################
      #   Score records - create schedule job                                               #
      #   This is the job configuration used for production inference                       #
      #######################################################################################
      - name: "ml-prod-deployment-score-records"
        git_source:
          git_url: https://github.com/marshackVB/ml_prod_deployment.git
          git_provider: "github"
          git_branch: "master"
        schedule: 
          quartz_cron_expression: "35 0 0 * * ?"
          timezone_id: "UTC"
          pause_status": "UNPAUSED"
        tasks:
          - task_key: "train-model"
            <<: *basic-static-cluster
            notebook_task:
              notebook_path: "ml_prod_deployment/inference"
            max_retries: 10
            min_retry_interval_millis: 900000
            retry_on_timeout: false
            timeout_seconds: 0
            email_notifications: {"marshall.carter@databricks.com"}
            deployment_config:
              no_package: true